import { Translation } from 'primeng/api';

/** Textos internos dos componentes PrimeNG em português. */
export const PRIMENG_PT_BR: Translation = {
  accept: 'Sim',
  reject: 'Não',
  cancel: 'Cancelar',
  clear: 'Limpar',
  apply: 'Aplicar',
  choose: 'Escolher',
  upload: 'Enviar',
  startsWith: 'Começa com',
  contains: 'Contém',
  notContains: 'Não contém',
  endsWith: 'Termina com',
  equals: 'Igual a',
  notEquals: 'Diferente de',
  noFilter: 'Sem filtro',
  lt: 'Menor que',
  lte: 'Menor ou igual a',
  gt: 'Maior que',
  gte: 'Maior ou igual a',
  matchAll: 'Todas as regras',
  matchAny: 'Qualquer regra',
  addRule: 'Adicionar regra',
  removeRule: 'Remover regra',
  emptyMessage: 'Nenhum registro encontrado',
  emptyFilterMessage: 'Nenhum resultado encontrado',
  emptySearchMessage: 'Nenhum resultado encontrado',
  emptySelectionMessage: 'Nenhum item selecionado',
  selectionMessage: '{0} itens selecionados',
  searchMessage: '{0} resultados disponíveis',
  pending: 'Pendente',
  today: 'Hoje',
  dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
  dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
  monthNames: [
    'Janeiro',
    'Fevereiro',
    'Março',
    'Abril',
    'Maio',
    'Junho',
    'Julho',
    'Agosto',
    'Setembro',
    'Outubro',
    'Novembro',
    'Dezembro',
  ],
  monthNamesShort: [
    'Jan',
    'Fev',
    'Mar',
    'Abr',
    'Mai',
    'Jun',
    'Jul',
    'Ago',
    'Set',
    'Out',
    'Nov',
    'Dez',
  ],
  dateFormat: 'dd/mm/yy',
  firstDayOfWeek: 0,
  aria: {
    close: 'Fechar',
    previous: 'Anterior',
    next: 'Próximo',
    navigation: 'Navegação',
    pageLabel: 'Página {page}',
    firstPageLabel: 'Primeira página',
    lastPageLabel: 'Última página',
    nextPageLabel: 'Próxima página',
    prevPageLabel: 'Página anterior',
    previousPageLabel: 'Página anterior',
    rowsPerPageLabel: 'Linhas por página',
    jumpToPageDropdownLabel: 'Ir para a página',
    jumpToPageInputLabel: 'Ir para a página',
    selectAll: 'Selecionar todos',
    unselectAll: 'Desmarcar todos',
    removeLabel: 'Remover',
    maximizeLabel: 'Maximizar',
    minimizeLabel: 'Minimizar',
  },
};
